version: "3.3"
services:
  api:
    image: model_app
    environment:
      - API_BASE=${API_BASE}
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    depends_on:
      - postgres
    working_dir: /app/src
    command: gunicorn --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 main:app

  nginx:
    restart: always
    image: nginx
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - ../nginx/simple_config.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api

  postgres:
    image: "postgres:13"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ../postgres:/docker-entrypoint-initdb.d:ro